[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.0"
evm_version = "istanbul"
use_literal_content = true
bytecode_hash = "ipfs"
optimizer_runs = 200
libraries = []

[profile.default.optimizer_details]
peephole = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true
yul = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
